# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Francisco Barrios
title: Android Developer
email: fbarrios80@gmail.com

# Social links
# twitter_username: facespics
github_username:  franciscobarrios
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: franciscobg80
stackoverflow_username: "1712446"
medium_username: azhagthott
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Francisco and I'm a passionate Android developer. 
  Not only have I experienced in mobile development, I also have experience in web apps. I've worked at a number of companies gaining teamwork and leadership skills.
  I am most skilled in: <mark>Android</mark>, <mark>Java</mark> and currently now I'm learning <mark>Kotlin</mark>

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Projects Section
# projects_title: Projects

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software development, some of my other interests and hobbies are:
   - Play guitar
   - Travel
   - Fitness

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag